name: Backend Health Check

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Health Check
        run: |
          echo "Checking health at ${{ secrets.NEXT_APP_URL }}/api/health"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" ${{ secrets.NEXT_APP_URL }}/api/health)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Health check failed with status code $STATUS_CODE"
            curl -v ${{ secrets.NEXT_APP_URL }}/api/health  # Verbose output for debugging
           exit 1
          else
           echo "Health check passed with status code $STATUS_CODE"
            fi

      - name: Send Slack Notification on Failure
        if: ${{failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload="{
            \"text\": \"❌ Backend health check failed. Please investigate.\",
            \"attachments\": [
              {
              \"color\": \"#ff0000\",
              \"fields\": [
                {
                  \"title\": \"Service\",
                  \"value\": \"Backend\",
                  \"short\": true
                },
                {
                  \"title\": \"Status\",
                  \"value\": \"Failed\",
                  \"short\": true
                },
                {
                  \"title\": \"URL\",
                  \"value\": \"${{ secrets.NEXT_APP_URL }}/api/health\",
                  \"short\": false
                }
              ]
            }
          ]
          }"
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"

      - name: Send Slack Notification on Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          payload="{
          \"text\": \"✅ Backend health check passed successfully.\",
          \"attachments\": [
            {
              \"color\": \"#36a64f\",
              \"fields\": [
                {
                  \"title\": \"Service\",
                  \"value\": \"Backend\",
                  \"short\": true
                },
                {
                  \"title\": \"Status\",
                  \"value\": \"Success\",
                  \"short\": true
                },
                {
                  \"title\": \"URL\",
                  \"value\": \"${{ secrets.NEXT_APP_URL }}/api/health\",
                  \"short\": false
                }
              ]
            }
          ]
          }"
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
