name: Backend Health Check

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Health Check
        run: |
          echo "Checking health at ${{ secrets.NEXT_APP_URL }}/api/health"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" ${{ secrets.NEXT_APP_URL }}/api/health)
          if [ "$STATUS_CODE" -ne 200 ]; then
             echo "Health check failed with status code $STATUS_CODE"
             curl -v ${{ secrets.NEXT_APP_URL }}/api/health  # Verbose output for debugging
           exit 1
          else
           echo "Health check passed with status code $STATUS_CODE"
            fi
